katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import register
from todolist.views import login_user
from todolist.views import logout_user
from todolist.views import show_todolist
from todolist.views import create_task
from todolist.views import change_done
from todolist.views import remove_task
from todolist.views import add_todolist_item
from todolist.views import get_todolist_json
app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create_task'),
    path('change-done/<int:id>', change_done, name='change_done'),
    path('remove-task/<int:id>', remove_task, name='remove_task'),
    path('add/', add_todolist_item, name='add_todolist_item'),
    path('json/', get_todolist_json, name='get_todolist_json'),
]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE, blank = True, null = True)
    date = models.DateField(auto_now_add = True)
    title = models.TextField()
    description = models.TextField()
    is_finished = models.BooleanField(default = False)

todolist/forms.py
from django import forms
from .models import Task

class TodoList(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('title', 'description')

        widgets = {
            'title': forms.TextInput(attrs={'placeholder':'Input Judul Task', 'class':'form-control mx-3 my-2'}),
            'description': forms.Textarea(attrs={'placeholder':'Input Judul Task', 'class':'form-control mx-3 my-2'})
        }

todolist/views.py
from hashlib import new
from multiprocessing import context
from django.shortcuts import render, redirect, get_object_or_404
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
import todolist
from todolist.forms import TodoList
from todolist.models import Task
from django.http import JsonResponse, HttpResponse, HttpResponseNotFound
from django.core import serializers


@login_required(login_url='/todolist/login/')
def show_todolist(request):
    todo = Task.objects.filter(user=request.user)
    context = {
        'list_todolist' : todo,
        'username' : request.user.username,
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "todolist.html", context)

# Create your views here.
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)


def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/todolist/login/')
def create_task(request):
    form = TodoList()
    if request.method == "POST":
        form = TodoList(request.POST)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.user = request.user
            new_task.save() 
            return redirect('todolist:show_todolist')
    
    context = {'form':form}
    return render(request, 'create_task.html', context)

@login_required(login_url='/todolist/login/')
def get_todolist_json(request):
    todolist_item = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", todolist_item), content_type="application/json")

@login_required(login_url='/todolist/login/')
def add_todolist_item(request):
    if request.method == 'POST':
        task_title = request.POST.get("title")
        task_description = request.POST.get("description")
        user = request.user
        date = datetime.now()
        is_finished = False
        new_task = Task(user=user, date=date, title=task_title, description=task_description, is_finished=is_finished)
        new_task.save()
        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()


def remove_task(request, id):
    deletion = Task.objects.filter(id=id)
    deletion.delete()
    return redirect('todolist:show_todolist')

def change_done(request, id):
    change = Task.objects.get(id = id)
    change.is_finished = not(change.is_finished)
    change.save()
    return redirect('todolist:show_todolist')



        

todolist/templates/create_task.html
{% extends 'base.html' %}
{% block meta %}

<title>Create Task</title>

{% endblock meta %}

{% block content %}
<div class="create_task">
    <p class="'text">
        CREATE TASK
    </p>
    <form method="POST">
        <div class="'w_screen">
            {% csrf_token %}
            <div class="w_full">
                <table  class="">  
                    {{ form.as_table }}          
                </table>  
            </div>
        </div>
    </form>
</div>

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
<style>
    body {
        font-family: 'Algreya Sans SC', sans-serif;
        background-color: cornflowerblue;
        height: 100vh;
        display: flex;
        align-items: center;
        justify-content: center;
    }
    .login {
    padding: 40px;
    border-radius: 20px;
    background-color: lightgoldenrodyellow;
    }
    .btn-primary{
        background-color: lightblue;
        border-color: lightpink;
    }
</style>
{% endblock meta %}

{% block content %}

<div class="login">
    <p class="h3 text-center">Login</p>
    <hr />
    
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-light" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <form method="POST" action="" class="form-container">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" name="username" class="form-control mb-2" id="username" placeholder="Username">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" name="password" class="form-control mb-2" id="password" placeholder="Password">
        </div>
        <input class="login_btn btn btn-primary my-2" type="submit" value="Login">
    </form>
            
    <hr />
    <div class="text-center">
        Belum mempunyai akun? <a href="{% url 'todolist:register' %}" style="color: navy;" >Buat Akun</a>
    </div>     
</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}
<title>Registrasi Akun Baru</title>
<style>
    body {
        font-family: 'Algreya Sans SC', sans-serif;
        background-color: lightskyblue;
        height: 100vh;
        display: flex;
        align-items: center;
        justify-content: center;
    }
    .register {
    padding: 40px;
    border-radius: 20px;
    background-color: lightgoldenrodyellow;
    }
    .btn-primary{
        background-color: lightblue;
        border-color: lightpink;
    }
</style>
{% endblock meta %}


{% block content %}  

<div class = "register">
    <p class="h3 text-center">Formulir Registrasi</p>
    <hr />

    {% if messages %}  
        {% for message in messages %}  
            <div class="alert alert-secondary" role="alert">
                {{ message }}
            </div> 
        {% endfor %}  
    {% endif %}

    <form method="POST" class="form-container">  
        {% csrf_token %}  
        <table>  
            {{ form.as_table }}  
            <tr>  
                <td><input class="btn btn-primary my-2" type="submit" name="submit" value="Daftar"/></td>  
            </tr>  
        </table>  
    </form>
</div>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Registrasi Akun Baru</title>
<style>
    body {
        font-family: 'Algreya Sans SC', sans-serif;
        background-color: rgb(162, 194, 253);
        height: 100vh;
    }
  
    .navbar {
      background-color: lightgoldenrodyellow;
    }
    .btn-primary{
        background-color: lightblue;
        border-color: lightpink;
    }
    .btn-link{
      background-color: lightblue;
      border-color: lightpink;
      border: 1px;
    }

    .h1{
      font-size: xx-large;
      font-weight: bold;
    }

    .h5 {
      font-size: medium;
      font-weight: lighter;
    }

    .card:hover{
    transform: scale(1.5);
    background-color: cyan;
  } 
  

  
</style>
{% endblock meta %}

{% block content %}

<nav class="navbar navbar-expand-lg navbar-light sticky-top">
    <a class="navbar-brand" href="#">TODO LIST</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link active" href="https://pbp-fasilkom-ui.github.io/ganjil-2023/">Link Github PBP <span class="sr-only">(current)</span></a>
        </div>
        <form class="form-inline my-2 my-lg-0">
            <button class="btn btn-outline-primary"><a href="{% url 'todolist:logout' %}" class="btn-link">Logout</a></button>
        </form>
    </div>
</nav>

<p class="h1 m-4">{{username}}'s To-Do List</p>
<p class="h5 m-4">Sesi terakhir login: {{ last_login }}</p>

<button type="button" class="btn btn-primary mx-5" data-toggle="modal" data-target="#exampleModal">Add TodoList</button>

<div class="container-fluid m-2">
    <div class="row" id="cards"></div>
</div>

  
  <!-- Modal: taken form bootstrap website --> 
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Add New TodoList</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
            <form id="form-myform" onsubmit="return false;">
                <div class="modal-body">
                    {% csrf_token %}
                    <div class="form-group">
                     <form role="'form" method="POST" action="" id="form" onsubmit="return false;"> 
                        <input type="hidden" name="_token" value=""> 
                            <label for="title" class="control-label">Judul Task</label>
                            <div>
                                <input type="text" class="form-control input-lg" name="title" placeholder="title" id="title">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="description" class="control-label">Description</label>
                            <div>
                                <input type="text" class="form-control input-lg" name="description" placeholder="description" id="description">
                            </div>
                        </div>
                         <div class="form-group">
                            <button type="submit" class="btn btn-primary" id="savebutton">Save changes</button>
                        </div> 
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </form>
      </div>
    </div>
  </div> 



  <script>
    async function getTodolist() {
        return fetch("{% url 'todolist:get_todolist_json' %}").then((res) => res.json())
    }
  
    async function refreshTodolist() {
        document.getElementById("title").value = ""
        document.getElementById("description").value = ""
        document.getElementById("cards").innerHTML = ""
        const todolist = await getTodolist()
        let htmlString = ""
        todolist.forEach((task) => {
            let is_finished = task.fields.is_finished ? "Selesai" : "Belum Selesai";
            htmlString += `\n<div class="col-lg-3 col-md-4 col-sm-6">
                                    <div id="${task.pk}" class="card my-3" style="width: 18rem;">
                                        <div class="card-body">
                                            <h5 class="card-title">${task.fields.title}
                                                <span class="badge badge-secondary">
                                                    ${is_finished}
                                                </span>
                                            </h5>
                                            <h6 class="card-subtitle my-2 text-muted">Created on ${task.fields.date}</h6>
                                            <p class="card-text">${task.fields.description}</p>
                                            <button class="btn btn-primary btn-sm m-2"><a href="change-done/${task.pk}" class="btnlink">Change Status</a></button>
                                            <button class="btn btn-danger btn-sm m-2"><a href="remove-task/${task.pk}" class="btnlink">Remove Task</a></button>
                                        </div>
                                    </div>
                                </div>`
        })
        
         document.getElementById("cards").innerHTML = htmlString
    }

    function addTodolist() {
        fetch("{% url 'todolist:add_todolist_item' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form-myform'))
        }).then(refreshTodolist)
        return false
    }

    document.getElementById("savebutton").onclick = addTodolist
    refreshTodolist()

</script>

{% endblock content %}